language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - REPO_NAME=cakephp-uni-login
    - PLUGIN_NAME=UniLogin
    - REQUIRE=""
    - DB=mysql CAKE_VERSION=2

  matrix:
    - DB=mysql CAKE_VERSION=2.6
    - DB=mysql CAKE_VERSION=2.7
    - DB=mysql CAKE_VERSION=2.8
    - DB=mysql CAKE_VERSION=2.9
    - DB=mysql CAKE_VERSION=2.10

matrix:
  include:
    - php: 7.1
      env:
        - CODECOVERAGE=1
    - php: 7.1
      env:
        - PHPCS=1
    - php: 7.1
      env:
        - FOC_VALIDATE=1
  exclude:
    - php: 7.0
      env: DB=mysql CAKE_VERSION=2.6
    - php: 7.0
      env: DB=mysql CAKE_VERSION=2.7
    - php: 7.0
      env: DB=mysql CAKE_VERSION=2.8
    - php: 7.1
      env: DB=mysql CAKE_VERSION=2.6
    - php: 7.1
      env: DB=mysql CAKE_VERSION=2.7
    - php: 7.1
      env: DB=mysql CAKE_VERSION=2.8

branches:
  only:
    - master

before_script:
  - git clone -b master https://github.com/Oefenweb/travis --depth 1 ../travis
  - travis_wait ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
  hipchat:
    rooms:
      secure: ccO982kI5arY+N4n8MAksh3DHLKW1s6IhBQNVr3iytoA9Qnnnzx9Jrv/zVYCB7qbubu8RuyD7WSSJwQNxZ2inX15nHmhxRTgJBrNIsmRms8MgAKjEB+OCIc4vUkqmLk+3aCjzPuHLaF6aUXCrUQn+wBPggzQmb0HFqAvo4e3D1A=
